### ISSUE TITLE
Are there any updates on this project?

### ISSUE THREAD

**Issue by sjlongland** [mluckham54/openocd_bbb#1]
Hi,

Just stumbled on this whilst looking around for a JTAG implementation for the BeagleBone.  I have a PocketBeagle which I've wired up to a Lattice IceStick via PRU0, and plan to use PRU0 as a high-speed data link between the FPGA and the PocketBeagle.

One application of this was for JTAG, integrating that with OpenOCD.  The description of your project looked almost identical to what I was doing; just I'm using a low-end FPGA (with ~1200 LUTs) and yourself a CPLD.

I was hoping I'd be able to port your CPLD code across to the iCE40HX1k in the IceStick.  Sadly, all I can find is one commit adding a copy of the GPLv2 and the other adding a README.

**Comment by mluckham54** [comment]
Unfortunately the student on that project wasn't very active, and it
withered.  I don't think a CPLD board was made.  I did a bunch of research
to get data flowing between the Beaglebone core and the PRUs and there was
some code for that, but never integrated into OpenOCD.

Mike Luckham

**Comment by sjlongland** [comment]
No worries… it's unfortunate when a project loses momentum and stops like that.  As I say, it looked really close to what I'm already doing… thus in the interests of Not Re-Inventing the Wheel, I thought I'd take a look.

If you're able to throw up what code there was, maybe some of it can be rescued and brought up-to-date, but otherwise I appreciate your response.

Regards,
Stuart Longland
